config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
  root to: 'articles#index'

  resources :articles, :only => [:index, :show] do
    collection do
      get 'page/:page_id', to: 'articles#page'
      get 'daily/:year/:month/:day', to: 'articles#daily'
      get 'daily/:year/:month/:day/page/:page_id', to: 'articles#daily'
      get 'monthly/:year/:month', to: 'articles#monthly'
      get 'monthly/:year/:month/page/:page_id', to: 'articles#monthly'
      get 'search_by/:keyword', to: 'articles#search_by'
      get 'search_by/:keyword/page/:page_id', to: 'articles#search_by'
      get 'tag/:tag_id', to: 'articles#tag'
      get 'tag/:tag_id/page/:page_id', to: 'articles#tag'
    end
    member do
      post 'entry_comment'
    end
  end
  namespace :admin do
    resources :articles
    resources :comments
    resources :authorities
    resources :tags
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :article_id, presence: true
  validates :entry_user_id, presence: true
  belongs_to :article
  belongs_to :user, foreign_key: 'entry_user_id'

  scope :user_accessible, ->(authority_id) { includes(article: :authorities).order(created_at: :desc).where(authorities: {id: authority_id}) }
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :is_admin_accessible
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  layout 'admin_layout'

  # GET /comments
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to admin_comment_path(@comment), notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to admin_comment_path(@comment), notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to admin_comments_url, notice: 'Comment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:article_id, :content, :entry_user_id)
    end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/_form.html.haml
= form_for [:admin, @comment] do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :article_id, '記事ID:'
    = f.number_field :article_id

  .field
    = f.label :content, 'コメント:'
    = preserve f.text_area :content

  .field
    = f.label :entry_user_id, '投稿ユーザーID:'
    = f.number_field :entry_user_id

  .actions
    = f.submit '保存'

app/views/admin/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', admin_comment_path(@comment)
\|
= link_to 'Back', admin_comments_path

app/views/admin/comments/index.html.haml
%h1 Listing comments

%table
  %thead
    %tr
      %th 記事日時
      %th 記事タイトル
      %th コメント
      %th 投稿ユーザー
      %th
      %th
      %th

  %tbody
    - @comments.each do |comment|
      %tr
        %td= comment.article.entry_at
        %td= comment.article.title
        %td= comment.content
        %td= comment.user.name
        %td= link_to 'Show', admin_comment_path(comment)
        %td= link_to 'Edit', edit_admin_comment_path(comment)
        %td= link_to 'Destroy', admin_comment_path(comment), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Comment', new_admin_comment_path

app/views/admin/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', admin_comments_path

app/views/admin/comments/show.html.haml
%p
  %b 記事日時：
  = @comment.article.entry_at

%p
  %b 記事タイトル：
  = @comment.article.title

%p
  %b コメント：
  = @comment.content

%p
  %b 投稿ユーザー：
  = @comment.user.name

= link_to 'Edit', edit_admin_comment_path(@comment)
\|
= link_to 'Back', admin_comments_path