config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
  root to: 'articles#index'

  resources :articles, :only => [:index, :show] do
    collection do
      get 'page/:page_id', to: 'articles#page'
      get 'daily/:year/:month/:day', to: 'articles#daily'
      get 'daily/:year/:month/:day/page/:page_id', to: 'articles#daily'
      get 'monthly/:year/:month', to: 'articles#monthly'
      get 'monthly/:year/:month/page/:page_id', to: 'articles#monthly'
      get 'search_by/:keyword', to: 'articles#search_by'
      get 'search_by/:keyword/page/:page_id', to: 'articles#search_by'
      get 'tag/:tag_id', to: 'articles#tag'
      get 'tag/:tag_id/page/:page_id', to: 'articles#tag'
    end
    member do
      post 'entry_comment'
    end
  end
  namespace :admin do
    resources :articles
    resources :comments
    resources :authorities
    resources :tags
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  has_many :article_tags, dependent: :destroy
  has_many :articles, :through => :article_tags
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :is_admin_accessible
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  layout 'admin_layout'

  # GET /tags
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to admin_tag_path(@tag), notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      redirect_to admin_tag_path(@tag), notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_to admin_tags_url, notice: 'Tag was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/_form.html.haml
= form_for [:admin, @tag] do |f|
  - if @tag.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      %ul
        - @tag.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name, 'タグ名称:'
    = f.text_field :name

  .actions
    = f.submit '保存'

app/views/admin/tags/edit.html.haml
%h1 Editing tag

= render 'form'

= link_to 'Show', admin_tag_path(@tag)
\|
= link_to 'Back', admin_tags_path

app/views/admin/tags/index.html.haml
%h1 Listing tags

%table
  %thead
    %tr
      %th タグ名称
      %th
      %th
      %th

  %tbody
    - @tags.each do |tag|
      %tr
        %td= tag.name
        %td= link_to 'Show', admin_tag_path(tag)
        %td= link_to 'Edit', edit_admin_tag_path(tag)
        %td= link_to 'Destroy', admin_tag_path(tag), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tag', new_admin_tag_path

app/views/admin/tags/new.html.haml
%h1 New tag

= render 'form'

= link_to 'Back', admin_tags_path

app/views/admin/tags/show.html.haml
%p
  %b タグ名称：
  = @tag.name

= link_to 'Edit', edit_admin_tag_path(@tag)
\|
= link_to 'Back', admin_tags_path