config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
  root to: 'articles#index'

  resources :articles, :only => [:index, :show] do
    collection do
      get 'page/:page_id', to: 'articles#page'
      get 'daily/:year/:month/:day', to: 'articles#daily'
      get 'daily/:year/:month/:day/page/:page_id', to: 'articles#daily'
      get 'monthly/:year/:month', to: 'articles#monthly'
      get 'monthly/:year/:month/page/:page_id', to: 'articles#monthly'
      get 'search_by/:keyword', to: 'articles#search_by'
      get 'search_by/:keyword/page/:page_id', to: 'articles#search_by'
      get 'tag/:tag_id', to: 'articles#tag'
      get 'tag/:tag_id/page/:page_id', to: 'articles#tag'
    end
    member do
      post 'entry_comment'
    end
  end
  namespace :admin do
    resources :articles
    resources :comments
    resources :authorities
    resources :tags
  end
end

app/models/authority.rb
class Authority < ApplicationRecord
  validates :name, presence: true
  has_many :article_authorities, dependent: :destroy
  has_many :articles, :through => :article_authorities
  has_many :users, dependent: :destroy
end

app/controllers/admin/authorities_controller.rb
class Admin::AuthoritiesController < ApplicationController
  before_action :is_admin_accessible
  before_action :set_authority, only: [:show, :edit, :update, :destroy]
  layout 'admin_layout'

  # GET /authorities
  def index
    @authorities = Authority.all
  end

  # GET /authorities/1
  def show
  end

  # GET /authorities/new
  def new
    @authority = Authority.new
  end

  # GET /authorities/1/edit
  def edit
  end

  # POST /authorities
  def create
    @authority = Authority.new(authority_params)

    if @authority.save
      redirect_to admin_authority_path(@authority), notice: 'Authority was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /authorities/1
  def update
    if @authority.update(authority_params)
      redirect_to admin_authority_path(@authority), notice: 'Authority was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /authorities/1
  def destroy
    @authority.destroy
    redirect_to admin_authorities_url, notice: 'Authority was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authority
      @authority = Authority.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def authority_params
      params.require(:authority).permit(:name)
    end
end

app/helpers/admin/authorities_helper.rb
module Admin::AuthoritiesHelper
end

app/views/admin/authorities/_form.html.haml
= form_for [:admin, @authority] do |f|
  - if @authority.errors.any?
    #error_explanation
      %h2= "#{pluralize(@authority.errors.count, "error")} prohibited this authority from being saved:"
      %ul
        - @authority.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name, '権限名:'
    = f.text_field :name

  .actions
    = f.submit '保存'

app/views/admin/authorities/edit.html.haml
%h1 Editing authority

= render 'form'

= link_to 'Show', admin_authority_path(@authority)
\|
= link_to 'Back', admin_authorities_path

app/views/admin/authorities/index.html.haml
%h1 Listing authorities

%table
  %thead
    %tr
      %th 権限名
      %th
      %th
      %th

  %tbody
    - @authorities.each do |authority|
      %tr
        %td= authority.name
        %td= link_to 'Show', admin_authority_path(authority)
        %td= link_to 'Edit', edit_admin_authority_path(authority)
        %td= link_to 'Destroy', admin_authority_path(authority), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Authority', new_admin_authority_path

app/views/admin/authorities/new.html.haml
%h1 New authority

= render 'form'

= link_to 'Back', admin_authorities_path

app/views/admin/authorities/show.html.haml
%p
  %b 権限名：
  = @authority.name

= link_to 'Edit', edit_admin_authority_path(@authority)
\|
= link_to 'Back', admin_authorities_path