config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
  root to: 'articles#index'

  resources :articles, :only => [:index, :show] do
    collection do
      get 'page/:page_id', to: 'articles#page'
      get 'daily/:year/:month/:day', to: 'articles#daily'
      get 'daily/:year/:month/:day/page/:page_id', to: 'articles#daily'
      get 'monthly/:year/:month', to: 'articles#monthly'
      get 'monthly/:year/:month/page/:page_id', to: 'articles#monthly'
      get 'search_by/:keyword', to: 'articles#search_by'
      get 'search_by/:keyword/page/:page_id', to: 'articles#search_by'
      get 'tag/:tag_id', to: 'articles#tag'
      get 'tag/:tag_id/page/:page_id', to: 'articles#tag'
    end
    member do
      post 'entry_comment'
    end
  end
  namespace :admin do
    resources :articles
    resources :comments
    resources :authorities
    resources :tags
  end
end

app/views/layouts/admin_layout.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SincrareBlog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      %nav
        - if user_signed_in?
          %strong= current_user.email
          = link_to 'プロフィール変更', edit_user_registration_path
          |
          = link_to "ログアウト", destroy_user_session_path, method: :delete
        - else
          = link_to "サインイン", new_user_registration_path
          |
          = link_to "ログイン", new_user_session_path

    %p.notice= notice
    %p.alert= alert

    %nav
      %ul
        %li= link_to '記事一覧', admin_articles_path
        %li= link_to 'コメント一覧', admin_comments_path
        %li= link_to '権限一覧', admin_authorities_path
        %li= link_to 'タグ一覧', admin_tags_path
        -# %li= link_to 'ユーザー一覧', admin_users_path

    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => 'UTF-8'}/
    %title しんくれあ記
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => 'http://fonts.googleapis.com/css?family=Damion&subset=latin', :rel => 'stylesheet', :type => 'text/css'}
  %body
    %header
      = link_to image_tag('title.png', { alt: 'しんくれあ記'}), articles_path

    %main(role='main')
      %p.notice= notice
      %p.alert= alert
      %section.sidebar
        %aside
          - if user_signed_in?
            %h1 アカウント
            %strong= current_user.email
            %p
              = link_to 'プロフィール変更', edit_user_registration_path
              |
              = link_to 'ログアウト', destroy_user_session_path, method: :delete
          - else
            %h1 ログイン
            %p
              = link_to 'サインイン', new_user_registration_path
              |
              = link_to 'ログイン', new_user_session_path

        %aside
          %h1 プロフィール
          %p.name HN:しんくれあ
          %p 受託開発メインのIT企業に勤務するC#er。趣味は木工と読書です。これまでプライベートな日記がメインのブログでしたが、技術的な記事も書いていきたいと思います。

        %aside
          %h1 記事の検索
          .field
            %input{type: 'text', name: 'keyword', id: 'keyword'}
          .actions
            %input{type: 'button', value: '検索', onclick: "location.href='/articles/search_by/' + $('#keyword').val()" }

        %aside
          %h1 月選択
          - @monthly_articles_count.each do |monthly_articles|
            %ul.list
              %li= link_to '%s月%s日' % monthly_articles[0] + '(%s)' % monthly_articles[1], '/articles/monthly/%s/%s' % monthly_articles[0]

        %aside
          %h1 タグ
          - @tags.each do |tag|
            %ul.list
              %li= link_to tag.name, '/articles/tag/' + tag.id.to_s

        %aside
          %h1 最新コメント
          - @recent_comments.each do |comment|
            %ul.list
              = link_to article_path(comment.article, anchor: :comments) do
                = comment.entry_user_name
                %br
                = '→%s(%s)' % [comment.article.title, comment.created_at.strftime('%Y/%m/%d')]

      %section.articles
        = yield

    %footer
      %p Copyright (C) 2013 sincrare All Rights Reserved.